queue:
  build: .
  privileged: true
  ports:
    - 8080:8080

sut:
  build: testclient/
  command: bash -xec "a=$(curl http://${QUEUE_PORT_8080_TCP_ADDR}:${QUEUE_PORT_8080_TCP_PORT}/ping/1 | tr -d '\r') ; [[ $a == 'pong 1' ]]"
  links:
     - queue
