FROM vizzbuzz/base-alpine
RUN apk update && apk add curl bash
#python python-dev git gcc bsd-compat-headers libevent-dev build-base && \
#    curl https://bootstrap.pypa.io/ez_setup.py  | python
#RUN git clone git://github.com/Lawouach/WebSocket-for-Python.git && cd WebSocket-for-Python  && git checkout v0.2.4 && python setup.py install
#RUN git clone git://github.com/progrium/wssh.git && \
#    cd wssh  && \
#    python setup.py install
